LIB=$1
CURRENTDIR=$2
SPE_TYPE=$3
FUNDIR=$CURRENTDIR/MCP.fundir/

FDR="D11_STA_GEM"

cat ${CURRENTDIR}/${LIB}/D04_SNBC_READ/R04aI_GEMCLASS/*_GEMLINE.${SPE_TYPE}|wc -l > G00_ALL_GEM.sta
cat ${CURRENTDIR}/${LIB}/D04_SNBC_READ/R04aI_GEMCLASS/*_GEMLINE.${SPE_TYPE}.S|wc -l > G01_singl.${SPE_TYPE}rag.sta
cat ${CURRENTDIR}/${LIB}/D04_SNBC_READ/R04aI_GEMCLASS/*_GEMLINE.${SPE_TYPE}.E ../D04_SNBC_READ/R04aI_GEMCLASS/*_GEMLINE.${SPE_TYPE}.A |wc -l> G02_mult.${SPE_TYPE}rags.sta
cat ${CURRENTDIR}/${LIB}/D04_SNBC_READ/R04aI_GEMCLASS/*_GEMLINE.${SPE_TYPE}.A |wc -l> G03_intra.sta
cat ${CURRENTDIR}/${LIB}/D04_SNBC_READ/R04aI_GEMCLASS/*_GEMLINE.${SPE_TYPE}.E|wc -l > G04_inter.sta
cat ${CURRENTDIR}/${LIB}/D04_SNBC_READ/R04aI_GEMCLASS/*_GEMLINE.${SPE_TYPE}.E.A |wc -l> G05_inter_intra.sta
cat ${CURRENTDIR}/${LIB}/D04_SNBC_READ/R04aI_GEMCLASS/*_GEMLINE.${SPE_TYPE}.E.S|wc -l > G06_inter_single.sta
cat ${CURRENTDIR}/${LIB}/D05_TABLE/${LIB}_COMBINED_SA.GENSUB.bsv.gff.GEMLINE_OUT.tsv|grep -v "GEM_ID" |wc -l > G07_Total_SA.sta
module load python/2.7.9
python ${FUNDIR}/PX_1101_FRAG_DIST.py ${CURRENTDIR}/${LIB}/D05_TABLE/${LIB}_COMBINED_SA.GENSUB.bsv.gff.GEMLINE_OUT.tsv



cd ../


