
OUTSIDE=`pwd`
source ${OUTSIDE}/MCP.conf
source ${OUTSIDE}/MCP.module
source ${OUTSIDE}/MCP.tools

FDR=$LIB/D05_TABLE
cd $FDR
F=${LIB}_COMBINED_SA.SUBGEM.bsv.gff.GEMLINE_OUT.tsv.BE2_FRAGNUM.bedpe_PlinePpair.MID_LOOP

module load juicer/1.7.5

juicer1="/opt/compsci/juicer/1.7.5/CPU/common/"
juicer2="/opt/compsci/juicer/1.7.5/"

java -Xmx64g -jar ${juicer2}juicer.jar pre -r 2500000,1000000,500000,250000,100000,50000,25000,10000,5000,1000 $F $F.hic $HIC_GENOME_SIZE



wait
pwd
ls -l *.hic

cd $OUTSIDE




